### ISSUE TITLE
Error: Cannot convert value to TTL

### ISSUE THREAD

**Issue by fernandodiacenco** [Tronic/named1#1]
Hello,

I installed named1 on a Debian 11 VM with those commands:

```
sudo su

apt install python3-pip git redis -y

pip3 install git+https://github.com/Tronic/named1.git

python3 -m named1
```

After running and trying from a client machine, client has no answer, and the console returns this error:

![image](https://user-images.githubusercontent.com/2643364/165822574-c2708107-443e-4f31-baec-499c6a27b24b.png)

Perhaps I'm missing some configuration? Thanks.

**Comment by Tronic** [comment]
@fernandodiacenco Please see if that patch fixes your issue. Thanks for reporting!

**Comment by fernandodiacenco** [comment]
It is working now, thank you!
